window .document .write(typeof 100 +"<br>");
window .document .write(typeof 73.9 +"<br>");
window .document .write(typeof nan +"<br>");
window .document .write(typeof "water" +"<br>");
window .document .write(typeof false +"<br>");
window .document .write(typeof 9 !=11 + "<br>");
window .document .write( "orang"+"e" + "<br>");
window .document .write("orange"-"s"+"<br>" );
window .document .write( ("4"+"8") + "<br>");
window .document .write( ("4"-"8") +"<br>");
window .document .write("name" + 3 +"<br>");
window .document .write ("name" - 3 +"<br>" );
window .document .write (82 * "word" + "<br>");
window .document .write(1 + "hello" + "<br>");
window .document .write("hello" + 1 + "<br>");
window .document .write(1+true +"<br>");
window .document .write("hello" + true +"<br>" );
window .document .write(typeof(Infinity)+"<br>");
window .document .write(1 == '1' + "<br>");
window .document .write(1==='1'+"<br>");
